.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DOPPEL" "1" "February 2013" "" ""
.
.SH "NAME"
\fBdoppel\fR \- copy and compile template directories
.
.SH "SYNOPSIS"
\fBdoppel\fR [\fB\-V\fR|\fB\-\-version\fR]
.
.P
\fBdoppel\fR \fI\fB\-d\fR|\fB\-\-data\fR \fIcontext\fR\fR \fIsource\fR \fIdestination\fR
.
.P
\fBdoppel\fR \fI\fB\-F\fR|\fB\-\-file\fR \fIcontext_file\fR\fR \fIsource\fR \fIdestination\fR
.
.SH "DESCRIPTION"
\fBDoppel\fR recursively copies files from a given directory and compiles all templates in the directory copy\.
.
.P
Data to interpolate into the directory templates must either be provided via the \fBd|\-\-data\fR or \fBF|\-\-file\fR flags\.
.
.SH "OPTIONS"
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Prints the current \fBdoppel\fR version\.
.
.TP
\fB\-d\fR, \fB\-\-data\fR \fIcontext\fR
[required] Data/context to interpolate into the templates\.
.
.TP
\fB\-F\fR, \fB\-\-file\fR \fIcontext_file\fR
[required] Input file with data/content to interpolate into the templates\.
.
.TP
\fB\-e\fR, \fB\-\-engine\fR \fIengine\fR
Template engine for compiling templates\. By default, \fBdoppel\fR uses underscore\. Available options are:
.
.IP
\fBunderscore\fR
.
.IP
\fBhandlebars\fR
.
.TP
\fB\-x\fR, \fB\-\-extension\fR \fIfile_extension\fR
Template extension to use\. At the compile stage, \fBdoppel\fR will find all files with a given file extension to denote the file as a template\. The compiled copy will be trimmed of the file extension (e\.g\. (input) example\.js\.given_file_extension \-> (output) example\.js)\. Each template has a default file extension, as follows:
.
.IP
\fBunderscore\fR: \fBjst\fR
.
.IP
\fBhandlebars\fR: \fBhandlebars\fR

